apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  selector:
    app: training-service
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  selector:
    app: monitoring-service
  ports:
    - port: 5000
      targetPort: 5000
    - port: 5001
      targetPort: 5001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: visualization-service
spec:
  selector:
    app: visualization-service
  ports:
    - port: 8501
      targetPort: 8501
  type: NodePort
